spring.application.name=user-service
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/user_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
app.kafka.topic.user-events=${APP_KAFKA_TOPIC_USER_EVENTS:user-events}

eureka.client.service-url.defaultZone=${EUREKA_URI:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true

spring.config.import=configserver:${CONFIG_SERVER_URI:http://localhost:8888}
management.endpoints.web.exposure.include=refresh,health,circuitbreakers,circuitbreakerevents
management.endpoint.health.show-details=always

resilience4j.circuitbreaker.instances.kafkaProducerCb.sliding-window-size=10
resilience4j.circuitbreaker.instances.kafkaProducerCb.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.kafkaProducerCb.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.kafkaProducerCb.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.kafkaProducerCb.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.kafkaProducerCb.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.kafkaProducerCb.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.kafkaProducerCb.register-health-indicator=true