spring.application.name=config-server
server.port=8888

spring.cloud.config.server.git.uri=https://github.com/WhyMChibisova/aston-stage2-config
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.search-paths=common, {application}